# Cleaning (credit_card -- Dataset)

In [65]:
import pandas as pd
import numpy as np

### Load Credit Card Dataset

In [66]:
df = pd.read_csv("credit_card.csv")
df.head(3)

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87.0,1/1/2023,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,chip,TRAVEL,4393.21,0
1,708083283,NaN,445,1,108.0,1/1/2023,Week-1,Q1,2023,NaN,2517,992,21,0.736,Swipe,Entertainmnt,69.44,0
2,708084558,Blue,140,0,106.0,1/1/2023,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,NaN,NaN,202.58,0

In [67]:
df.shape

(10108, 18)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10108 entries, 0 to 10107
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Client_Num             10108 non-null  int64
 1   Card_Category          9710 non-null   object
 2   Annual_Fees            10108 non-null  int64
 3   Activation_30_Days     10108 non-null  int64
 4   Customer_Acq_Cost      9859 non-null   float64
 5   Week_Start_Date        10108 non-null  object
 6   Week_Num               10108 non-null  object
 7   Qtr                    10108 non-null  object
 8   current_year           10108 non-null  int64
 9   Credit_Limit           9896 non-null   float64
 10  Total_Revolving_Bal    10108 non-null  int64
 11  Total_Trans_Amt        10108 non-null  int64
 12  Total_Trans_Vol        10108 non-null  int64
 13  Avg_Utilization_Ratio  9899 non-null   float64
 14  Use Chip               9861 non-null   object
 15  Exp Type               9857 non-null   object
 16  Interest_Earned        10108 non-null  float64
 17  Delinquent_Acc         10108 non-null  int64
dtypes: float64(4), int64(8), object(6)
memory usage: 1.4+ MB

In [69]:
df.isnull().sum()

Client_Num                 0
Card_Category            398
Annual_Fees                0
Activation_30_Days         0
Customer_Acq_Cost        249
Week_Start_Date            0
Week_Num                   0
Qtr                        0
current_year               0
Credit_Limit             212
Total_Revolving_Bal        0
Total_Trans_Amt            0
Total_Trans_Vol            0
Avg_Utilization_Ratio    209
Use Chip                 247
Exp Type                 251
Interest_Earned            0
Delinquent_Acc             0
dtype: int64

### Clean Card_Category Column
##### - Remove extra spaces
##### - Standardize text format
##### - Correct inconsistent values
##### - Fill missing values

In [70]:
df['Card_Category'].value_counts(dropna = False)

Card_Category
Blue        8482
Silver       571
NaN          398
Gold         167
 Blue        146
blue         145
Blu          143
Platinum      56
Name: count, dtype: int64

In [71]:
df['Card_Category'] = df['Card_Category'].str.strip().str.title()
df['Card_Category'] = df['Card_Category'].apply(lambda x:'Blue' if x == 'Blu' else x)
df['Card_Category'] = df['Card_Category'].bfill()
df['Card_Category'].value_counts(dropna = False)

Card_Category
Blue        9314
Silver       571
Gold         167
Platinum      56
Name: count, dtype: int64

In [72]:
df.head(5)

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87.0,1/1/2023,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,chip,TRAVEL,4393.21,0
1,708083283,Blue,445,1,108.0,1/1/2023,Week-1,Q1,2023,NaN,2517,992,21,0.736,Swipe,Entertainmnt,69.44,0
2,708084558,Blue,140,0,106.0,1/1/2023,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,NaN,NaN,202.58,0
3,708085458,Blue,250,1,NaN,1/1/2023,Week-1,Q1,2023,-1438.3,0,3940,82,0.000,NaN,Grocery,236.40,0
4,708086958,Blue,320,1,106.0,1/1/2023,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,fuel,1004.87,1

### Handle Missing Values in Customer Acquisition Cost

In [73]:
df['Customer_Acq_Cost'] = df['Customer_Acq_Cost'].bfill()

In [74]:
df.isnull().sum()

Client_Num                 0
Card_Category              0
Annual_Fees                0
Activation_30_Days         0
Customer_Acq_Cost          0
Week_Start_Date            0
Week_Num                   0
Qtr                        0
current_year               0
Credit_Limit             212
Total_Revolving_Bal        0
Total_Trans_Amt            0
Total_Trans_Vol            0
Avg_Utilization_Ratio    209
Use Chip                 247
Exp Type                 251
Interest_Earned            0
Delinquent_Acc             0
dtype: int64

### Clean Credit Limit Column
##### - Convert negative values to positive
##### - Fill missing values

In [77]:
df['Credit_Limit'] = df['Credit_Limit'].abs()
df['Credit_Limit'] = df['Credit_Limit'].ffill()

### Handle Missing Values in Avg_Utilization_Ratio

In [78]:
df['Avg_Utilization_Ratio'].value_counts()

Avg_Utilization_Ratio
0.000    2411
0.073      44
0.048      32
0.057      32
0.061      29
         ...
0.929       1
0.896       1
0.891       1
0.853       1
0.921       1
Name: count, Length: 962, dtype: int64

In [81]:
df['Avg_Utilization_Ratio'] = df['Avg_Utilization_Ratio'].fillna(method = 'bfill')

C:\Users\user\AppData\Local\Temp\ipykernel_20436\3794860451.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Avg_Utilization_Ratio'] = df['Avg_Utilization_Ratio'].fillna(method = 'bfill')

In [82]:
df.isnull().sum()

Client_Num                 0
Card_Category              0
Annual_Fees                0
Activation_30_Days         0
Customer_Acq_Cost          0
Week_Start_Date            0
Week_Num                   0
Qtr                        0
current_year               0
Credit_Limit               0
Total_Revolving_Bal        0
Total_Trans_Amt            0
Total_Trans_Vol            0
Avg_Utilization_Ratio      0
Use Chip                 247
Exp Type                 251
Interest_Earned            0
Delinquent_Acc             0
dtype: int64

### Clean Use Chip Column

##### - Standardize text
##### - Correct spelling
##### - Fill missing values

In [83]:
df['Use Chip'].value_counts()

Use Chip
Swipe      6608
Chip       2160
Online      528
 Swipe      178
Swip        170
Chip         72
CHIP         66
chip         51
Online       28
Name: count, dtype: int64

In [87]:
df['Use Chip'] = df['Use Chip'].str.strip().str.title()
df['Use Chip'].value_counts()

Use Chip
Swipe     6786
Chip      2349
Online     556
Swip       170
Name: count, dtype: int64

In [91]:
df['Use Chip'] = df['Use Chip'].apply(lambda x:'Swipe' if x == 'Swip' else x)
df['Use Chip'] = df['Use Chip'].ffill()

In [92]:
df.isnull().sum()

Client_Num                 0
Card_Category              0
Annual_Fees                0
Activation_30_Days         0
Customer_Acq_Cost          0
Week_Start_Date            0
Week_Num                   0
Qtr                        0
current_year               0
Credit_Limit               0
Total_Revolving_Bal        0
Total_Trans_Amt            0
Total_Trans_Vol            0
Avg_Utilization_Ratio      0
Use Chip                   0
Exp Type                 251
Interest_Earned            0
Delinquent_Acc             0
dtype: int64

### Clean Expense Type Column
##### - Standardize text
##### - Correct spelling
##### - Fill missing values

In [93]:
df['Exp Type'].value_counts()

Exp Type
Bills            2765
Entertainment    1874
Fuel             1617
Grocery          1502
Food             1094
Travel            651
 bills            116
Entertainmnt       67
FUEL               52
FOOD               51
fuel               40
TRAVEL             28
Name: count, dtype: int64

In [96]:
df['Exp Type'] = df['Exp Type'].str.strip().str.title()
df['Exp Type'].value_counts()

Exp Type
Bills            2881
Entertainment    1874
Fuel             1709
Grocery          1502
Food             1145
Travel            679
Entertainmnt       67
Name: count, dtype: int64

In [99]:
df['Exp Type'] = df['Exp Type'].apply(lambda x: 'Entertainment' if x == 'Entertainmnt' else x)
df['Exp Type'].value_counts(dropna = False)

Exp Type
Bills            2881
Entertainment    1941
Fuel             1709
Grocery          1502
Food             1145
Travel            679
NaN               251
Name: count, dtype: int64

In [102]:
df['Exp Type'] = df['Exp Type'].fillna(method = 'ffill')

C:\Users\user\AppData\Local\Temp\ipykernel_20436\2969471341.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Exp Type'] = df['Exp Type'].fillna(method = 'ffill')

In [103]:
df.isnull().sum()

Client_Num               0
Card_Category            0
Annual_Fees              0
Activation_30_Days       0
Customer_Acq_Cost        0
Week_Start_Date          0
Week_Num                 0
Qtr                      0
current_year             0
Credit_Limit             0
Total_Revolving_Bal      0
Total_Trans_Amt          0
Total_Trans_Vol          0
Avg_Utilization_Ratio    0
Use Chip                 0
Exp Type                 0
Interest_Earned          0
Delinquent_Acc           0
dtype: int64

### Remove Remaining Missing Values

In [105]:
df = df.dropna()

### Export Clean Credit Card Dataset

In [108]:
df.to_csv("cleaned_credit_card.csv",index = False)

# Cleaning (customer -- Dataset)

### Load Customer Dataset

In [109]:
df = pd.read_csv("customer.csv")
df.head(5)

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326.0,3.0
1,708083283,62,F,0,unknown,NaN,NJ,91750,NaN,no,no,cellular,Self Employeed,5225.0,NaN
2,708084558,32,F,1,unknown,married,NJ,91750,yes,no,no,unknown,Self Employeed,14235.0,2.0
3,708085458,38,M,2,uneducated,NaN,NY,91750,no,no,no,NaN,NaN,45683.0,1.0
4,708086958,48,M,4,Graduate,Single,TX,91750,YES,yes,no,Cellular,NaN,NaN,1.0

In [110]:
df.shape

(10108, 15)

In [111]:
df.isnull().sum()

Client_Num                   0
Customer_Age                 0
Gender                       0
Dependent_Count              0
Education_Level            218
Marital_Status             355
state_cd                     0
Zipcode                      0
Car_Owner                  343
House_Owner                  0
Personal_loan                0
contact                    319
Customer_Job               362
Income                     234
Cust_Satisfaction_Score    226
dtype: int64

### Clean Education_Level Column

##### - Remove extra spaces
##### - Standardize text format
##### - Correct inconsistent values
##### - Fill missing values

In [112]:
df['Education_Level'].value_counts()

Education_Level
Graduate         3842
High School      1831
Unknown          1366
Uneducated       1331
Post-Graduate     465
Doctorate         396
uneducated        152
unknown           149
graduate           76
GRADUATE           65
High school        48
HIGH SCHOOL        47
HighSchool         46
doctorate          21
DOCTORATE          16
post-graduate      15
Post Graduate      13
POST-GRADUATE      11
Name: count, dtype: int64

In [114]:
df['Education_Level'] = df['Education_Level'].str.strip().str.title()

In [115]:
df['Education_Level'].value_counts()

Education_Level
Graduate         3983
High School      1926
Unknown          1515
Uneducated       1483
Post-Graduate     491
Doctorate         433
Highschool         46
Post Graduate      13
Name: count, dtype: int64

In [116]:
df['Education_Level'] = df['Education_Level'].replace({
    'Highschool': 'High School',
    'Post Graduate': 'Post-Graduate'
})

In [117]:
df['Education_Level'].value_counts()

Education_Level
Graduate         3983
High School      1972
Unknown          1515
Uneducated       1483
Post-Graduate     504
Doctorate         433
Name: count, dtype: int64

In [118]:
df.isnull().sum()

Client_Num                   0
Customer_Age                 0
Gender                       0
Dependent_Count              0
Education_Level            218
Marital_Status             355
state_cd                     0
Zipcode                      0
Car_Owner                  343
House_Owner                  0
Personal_loan                0
contact                    319
Customer_Job               362
Income                     234
Cust_Satisfaction_Score    226
dtype: int64

In [120]:
df['Education_Level'].value_counts(dropna = False)

Education_Level
Graduate         3983
High School      1972
Unknown          1515
Uneducated       1483
Post-Graduate     504
Doctorate         433
NaN               218
Name: count, dtype: int64

In [122]:
df['Education_Level'] = df['Education_Level'].fillna(method = 'ffill')

C:\Users\user\AppData\Local\Temp\ipykernel_20436\2595177742.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Education_Level'] = df['Education_Level'].fillna(method = 'ffill')

In [123]:
df.isnull().sum()

Client_Num                   0
Customer_Age                 0
Gender                       0
Dependent_Count              0
Education_Level              0
Marital_Status             355
state_cd                     0
Zipcode                      0
Car_Owner                  343
House_Owner                  0
Personal_loan                0
contact                    319
Customer_Job               362
Income                     234
Cust_Satisfaction_Score    226
dtype: int64

### Clean Marital_Status Column

##### - Remove extra spaces
##### - Standardize text format
##### - Fill missing values

In [124]:
df['Marital_Status'].value_counts()

Marital_Status
Married    4807
Single     3899
Unknown     711
married     164
single       91
 Single      81
Name: count, dtype: int64

In [126]:
df['Marital_Status'] = df['Marital_Status'].str.strip().str.title()
df['Marital_Status'].value_counts(dropna = False)

Marital_Status
Married    4971
Single     4071
Unknown     711
NaN         355
Name: count, dtype: int64

In [128]:
df['Marital_Status'] = df['Marital_Status'].ffill()
df['Marital_Status'].value_counts(dropna = False)

Marital_Status
Married    5165
Single     4220
Unknown     723
Name: count, dtype: int64

### Clean Car_Owner Column

##### - Standardize text format
##### - Fill missing values

In [131]:
df['Car_Owner'].value_counts(dropna = False)

Car_Owner
no     5689
yes    3821
NaN     343
No      174
YES      81
Name: count, dtype: int64

In [133]:
df['Car_Owner'] = df['Car_Owner'].str.strip().str.title()

In [134]:
df['Car_Owner'].value_counts(dropna = False)

Car_Owner
No     5863
Yes    3902
NaN     343
Name: count, dtype: int64

In [136]:
df['Car_Owner'] = df['Car_Owner'].ffill()

### Clean Contact Column

##### - Standardize text format
##### - Fill missing values

In [137]:
df['contact'].value_counts()

contact
cellular     7042
unknown      1828
telephone     652
Cellular      196
Unknown        55
Telephone      16
Name: count, dtype: int64

In [139]:
df['contact'] = df['contact'].str.strip().str.title()

In [141]:
df['contact'].value_counts(dropna = False)

contact
Cellular     7238
Unknown      1883
Telephone     668
NaN           319
Name: count, dtype: int64

In [143]:
df['contact'] = df['contact'].ffill()

In [144]:
df.isnull().sum()

Client_Num                   0
Customer_Age                 0
Gender                       0
Dependent_Count              0
Education_Level              0
Marital_Status               0
state_cd                     0
Zipcode                      0
Car_Owner                    0
House_Owner                  0
Personal_loan                0
contact                      0
Customer_Job               362
Income                     234
Cust_Satisfaction_Score    226
dtype: int64

### Clean Customer_Job Column

##### - Standardize text format
##### - Correct inconsistent values
##### - Fill missing values

In [145]:
df['Customer_Job'].value_counts()

Customer_Job
Selfemployeed     2333
Businessman       1766
Govt              1525
Blue-collar       1424
White-collar      1385
Retirees           986
Self Employeed     242
businessman         47
 Businessman        38
Name: count, dtype: int64

In [148]:
df['Customer_Job'] = df['Customer_Job'].str.strip().str.title()

In [152]:
df['Customer_Job'].value_counts(dropna = False)

Customer_Job
Selfemployeed    2575
Businessman      1851
Govt             1525
Blue-Collar      1424
White-Collar     1385
Retirees          986
NaN               362
Name: count, dtype: int64

In [151]:
df['Customer_Job'] = df['Customer_Job'].replace({
    'Self Employeed': 'Selfemployeed'
})

In [154]:
df['Customer_Job'] = df['Customer_Job'].fillna(method = 'ffill')

C:\Users\user\AppData\Local\Temp\ipykernel_20436\3631865343.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Customer_Job'] = df['Customer_Job'].fillna(method = 'ffill')

In [155]:
df.isnull().sum()

Client_Num                   0
Customer_Age                 0
Gender                       0
Dependent_Count              0
Education_Level              0
Marital_Status               0
state_cd                     0
Zipcode                      0
Car_Owner                    0
House_Owner                  0
Personal_loan                0
contact                      0
Customer_Job                 0
Income                     234
Cust_Satisfaction_Score    226
dtype: int64

### Handle Missing Values in Income

In [159]:
df['Income'] = df['Income'].fillna(method = 'bfill')

C:\Users\user\AppData\Local\Temp\ipykernel_20436\2180912911.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Income'] = df['Income'].fillna(method = 'bfill')

### Handle Missing Values in Customer Satisfaction Score

In [161]:
df['Cust_Satisfaction_Score'].value_counts(dropna = False)

Cust_Satisfaction_Score
3.0    2990
4.0    2099
5.0    1976
2.0    1686
1.0    1131
NaN     226
Name: count, dtype: int64

In [163]:
df['Cust_Satisfaction_Score'] = df['Cust_Satisfaction_Score'].bfill()

### Final Data Validation

In [164]:
df.isnull().sum()

Client_Num                 0
Customer_Age               0
Gender                     0
Dependent_Count            0
Education_Level            0
Marital_Status             0
state_cd                   0
Zipcode                    0
Car_Owner                  0
House_Owner                0
Personal_loan              0
contact                    0
Customer_Job               0
Income                     0
Cust_Satisfaction_Score    0
dtype: int64

In [165]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10108 entries, 0 to 10107
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Client_Num               10108 non-null  int64
 1   Customer_Age             10108 non-null  int64
 2   Gender                   10108 non-null  object
 3   Dependent_Count          10108 non-null  int64
 4   Education_Level          10108 non-null  object
 5   Marital_Status           10108 non-null  object
 6   state_cd                 10108 non-null  object
 7   Zipcode                  10108 non-null  int64
 8   Car_Owner                10108 non-null  object
 9   House_Owner              10108 non-null  object
 10  Personal_loan            10108 non-null  object
 11  contact                  10108 non-null  object
 12  Customer_Job             10108 non-null  object
 13  Income                   10108 non-null  float64
 14  Cust_Satisfaction_Score  10108 non-null  float64
dtypes: float64(2), int64(4), object(9)
memory usage: 1.2+ MB

### Export Clean Customer Dataset

In [166]:
df.to_csv("cleaned_customer.csv", index = False)